dist: jammy
language: node_js
node_js:
  - 18

branches:
  only:
    - main

before_install:
  - echo "{\"bundleName\":\"alerts-examples\"}" > target.json
  - git remote add deployorigin https://${GH_TOKEN}@github.com/ibm/aiops-ui-extension-template.git
    
install:
  - npm ci

script:
  - npm run lint || true
  - npm run test || travis_terminate 1
  - npm run build || travis_terminate 1
  - npm run build:storybook || travis_terminate 1
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && npm run deploy:storybook:ci || echo "not deploying storybook"
